### ISSUE TITLE
Support for Fn::Cidr

### ISSUE THREAD

**Issue by hcourt** [mapbox/cloudfriend#102]
Cloudfriend should support the [Fn::Cidr](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-cidr.html) function.

**Comment by rclark** [comment]
While we're here, there are several other functions we should add support for [Fn::Transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-transform.html).
