### ISSUE TITLE
validate-template doesn't work correctly with aws profile/process credentials

### ISSUE THREAD

**Issue by drboyer** [mapbox/cloudfriend#116]
At least on my system, attempting to use an AWS profile that pulls credentials from a credential_process instead of having AWS access keys set in the environment causes the `validate-template` CLI tool to misbehave. When I run the command in such an environment, the program will hang for some time before eventually erroring out with the following error:

```
✘ invalid: Missing credentials in config
```

## Expected behavior

This CLI tool can properly fetch credentials from AWS profiles, including those that use process credentials.

**Comment by rclark** [comment]
Likely this is because the version of the aws-sdk-js is old in cloudfriend. ProcessCredentials were added somewhat recently.

**Comment by drboyer** [comment]
Resolved in v5.0.0 by #121.
