### ISSUE TITLE
cf.cidr does not work

### ISSUE THREAD

**Issue by eternaltyro** [mapbox/cloudfriend#124]
For some reason cidr function does not work and I'm unable to figure out why. 

```
Could not parse template: Failed to parse /home/eternaltyro/workbench/hotosm-network/cloudformation/hotosm-network.template.js: cf.cidr is not a function
```

```
~/w/h/cloudformation » npm list -g --prefix ~/.node_modules @mapbox/cloudfriend
/home/eternaltyro/.node_modules/lib
└── @mapbox/cloudfriend@5.0.1
```

Here's the resource block

```
const Parameters = {
  DeploymentEnvironment: {
    Type: 'String',
    Description: 'One of "demo", "staging", or "production"'
  },
  AvailabilityZones: {
    Type: 'List',
    Default: cf.getAzs(cf.region)
  },
  VPCCidr: {
    Type: 'String',
    Default: '172.31.0.0/16'
  },
};

const Resources = {
  VirtualPrivateCloud: {
    Type: 'AWS::EC2::VPC',
    Properties: {
      Tags: [ ]
    }
  },
   PublicSubnetA: {
     Type: 'AWS::EC2::Subnet',
     Properties: {
        VpcId: cf.ref('VirtualPrivateCloud'),
       AssignIpv6AddressOnCreation: true,
       AvailabilityZone: cf.select(0, cf.ref('AvailabilityZones')),
       CidrBlock: cf.select(0, cf.cidr(cf.ref('VPCCidr'), 12, 8)),
       MapPublicIpOnLaunch: true,
       Tags: [ ]
     }
   },
   ...
 };
 ```

**Comment by rclark** [comment]
I'm not exactly sure what is causing your error `cf.cidr is not a function`, but I suspect something local  to your environment. Perhaps the `cf` variable isn't referring to the version of cloudfriend that you think it is referring to. 

I double-checked this against [a test-case I captured here](https://gist.github.com/rclark/7347da31fe9a67c0496574f89eb90b40). The `cf.cidr` function appears to do what it is supposed to do.

**Comment by eternaltyro** [comment]
Thank you, @rclark . It was likely because of my setup (`nvm`) messing with the `$NODE_PATH`. I fixed it by installing `@mapbox/cloudfriend` locally for the project..
