### ISSUE TITLE
1.8.0 and 1.8.1 releases on NPM

### ISSUE THREAD

**Issue by bjacobel** [mapbox/cloudfriend#19]
Hi there,

I see that [1.8.0](https://github.com/mapbox/cloudfriend/releases/tag/v1.8.0) and [1.8.1](https://github.com/mapbox/cloudfriend/releases/tag/v1.8.1) releases have been cut for GitHub Releases, but neither is available yet on NPM. Do you have plans to release these two versions to NPM?

Thanks!

**Comment by mapsam** [comment]
Howdy @bjacobel - looks like these have been published according to `npm view @mapbox/cloudfriend`:

```
{ name: '@mapbox/cloudfriend',
  description: 'Helper functions for assembling CloudFormation templates in JavaScript',
  'dist-tags': { latest: '1.8.1' },
  versions: [ '1.7.0', '1.8.0', '1.8.1' ],
...
```

Cheers!

**Comment by bjacobel** [comment]
@mapsam What about the [`cloudfriend`](https://www.npmjs.com/package/cloudfriend) package (no namespace)?

**Comment by mapsam** [comment]
Ah, we must have missed marking the non-scoped package as deprecated. All new updates will be at `@mapbox/cloudfriend` after we transitioned a majority of our modules to the `@mapbox` scope. 

1.7.0 has been marked as deprecated and now suggests to update to the scoped package.

```
npm WARN deprecated cloudfriend@1.7.0: This module is now under the @mapbox namespace: install @mapbox/cloudfriend instead
```

**Comment by bjacobel** [comment]
Makes sense, thanks!
