### ISSUE TITLE
Hookshot: Unable to read X-GitHub-Event header to determine event type

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/cloudfriend#40]
I guess it's a suggested "best practice" to determine your GitHub event type by looking at the `X-GitHub-Event` HTTP header ([docs](https://developer.github.com/v3/guides/best-practices-for-integrators/#check-the-event-type-and-action-before-processing-the-event)). Instead of duck typing.

This isn't possible in a GH hookshot right now because the HTTP headers are not being passed to your Lambda — [only the event body](https://github.com/mapbox/cloudfriend/blob/7f3652feeb8ee7437e1e526560940d3093343bf3/lib/shortcuts/hookshot.js#L385).

Unfortunately, I don't know how we could *add* that `X-GitHub-Event` information without a breaking change, since we'd need to change the data structure of the `event` that the Lambda receives. Any hot ideas?

**Comment by rclark** [comment]
I guess I'd rather just duck type 🤷‍♂️ 

The only other reasonable approach would be breaking, yes. If duck-typing isn't enough, then we just break it and include headers & body in the event pushed to the userland Lambda.
