### ISSUE TITLE
ServiceRole shortcut has incorrect Principal for some services (like ECS) in China

### ISSUE THREAD

**Issue by jseppi** [mapbox/cloudfriend#56]
Cloudfriend uses `${AWS::URLSuffix}` which only works in China sometimes. ECS is one of the times it does not work. `'ecs-tasks.amazonaws.com'` is the correct Principal in China.

https://github.com/mapbox/cloudfriend/blob/430543b27f49422a749447d9beb4a2fb779a3dac/lib/shortcuts/service-role.js#L61-L63

What are the others for which using `${AWS::URLSuffix}` are incorrect?

**Comment by freenerd** [comment]
Some important ones we found through trial and error:

- apigateway.amazonaws.com
- cloudformation.amazonaws.com
- s3.amazonaws.com
- autoscaling.amazonaws.com
- lambda

**Comment by rclark** [comment]
> What are the others for which using ${AWS::URLSuffix} are incorrect?

Have you scoured AWS docs for this yet, or even asked support whether or not this is documented somewhere?

In the meantime I should be able to offer a fix for the services listed above today.

**Comment by rclark** [comment]
Fix was published in v2.8.1.

**Comment by jseppi** [comment]
Thanks for the quick turnaround, @rclark!
